/*
 * WordListGeneratorView.java
 */

package wordlistgenerator;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import wordlistgenerator.bl.CustomWordListGen;
import wordlistgenerator.bl.GetURLContent;
import wordlistgenerator.bl.WordListGen;
import wordlistgenerator.bl.WordsListGen;
import wordlistgenerator.utility.FileManager;

/**
 * The application's main frame.
 */
public class WordListGeneratorView extends FrameView {
    private WordListGeneratorProgressBar jProgressBar;
    public WordListGeneratorView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = WordListGeneratorApp.getApplication().getMainFrame();
            aboutBox = new WordListGeneratorAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        WordListGeneratorApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtWordList = new javax.swing.JTextArea();
        jChkRemoveDuplicateCustom = new javax.swing.JCheckBox();
        generateButton = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jtxtURL = new javax.swing.JTextField();
        jChkRemoveDuplicate = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jrdbSimpleNumber = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTxtStart = new javax.swing.JTextField();
        jTxtEnd = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jrdbSimpleAZaz = new javax.swing.JRadioButton();
        jcmbCapSmall = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jcmbCapSmallLength = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jrdbSimpleCustom = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jcmbCustomLength = new javax.swing.JComboBox();
        jtxtCharacterList = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jrdbUrl = new javax.swing.JPanel();
        jrdbSimple = new javax.swing.JRadioButton();
        jrdbCustom = new javax.swing.JRadioButton();
        jrdbURL = new javax.swing.JRadioButton();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        settingMenu = new javax.swing.JMenu();
        genSettingMenuItem = new javax.swing.JMenuItem();
        smtpSettingMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();

        mainPanel.setName("mainPanel"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(wordlistgenerator.WordListGeneratorApp.class).getContext().getResourceMap(WordListGeneratorView.class);
        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(0), resourceMap.getString("jPanel7.border.title"))); // NOI18N
        jPanel7.setName("jPanel7"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jtxtWordList.setColumns(20);
        jtxtWordList.setRows(5);
        jtxtWordList.setName("jtxtWordList"); // NOI18N
        jScrollPane1.setViewportView(jtxtWordList);

        jChkRemoveDuplicateCustom.setText(resourceMap.getString("jChkRemoveDuplicateCustom.text")); // NOI18N
        jChkRemoveDuplicateCustom.setName("jChkRemoveDuplicateCustom"); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jChkRemoveDuplicateCustom)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1079, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jChkRemoveDuplicateCustom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
        );

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(wordlistgenerator.WordListGeneratorApp.class).getContext().getActionMap(WordListGeneratorView.class, this);
        generateButton.setAction(actionMap.get("generateWordList")); // NOI18N
        generateButton.setText(resourceMap.getString("generateButton.text")); // NOI18N
        generateButton.setName("generateButton"); // NOI18N

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(0), resourceMap.getString("jPanel8.border.title"))); // NOI18N
        jPanel8.setName("jPanel8"); // NOI18N

        jPanel10.setName("jPanel10"); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jtxtURL.setName("jtxtURL"); // NOI18N

        jChkRemoveDuplicate.setText(resourceMap.getString("jChkRemoveDuplicate.text")); // NOI18N
        jChkRemoveDuplicate.setName("jChkRemoveDuplicate"); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jChkRemoveDuplicate))
                .addContainerGap())
            .addComponent(jtxtURL, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jChkRemoveDuplicate)
                .addGap(4, 4, 4)
                .addComponent(jtxtURL, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(0), resourceMap.getString("jPanel1.border.title"))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jPanel3.setName("jPanel3"); // NOI18N

        buttonGroup2.add(jrdbSimpleNumber);
        jrdbSimpleNumber.setSelected(true);
        jrdbSimpleNumber.setText(resourceMap.getString("jrdbSimpleNumber.text")); // NOI18N
        jrdbSimpleNumber.setName("jrdbSimpleNumber"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jTxtStart.setName("jTxtStart"); // NOI18N

        jTxtEnd.setName("jTxtEnd"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrdbSimpleNumber)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtStart, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(516, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrdbSimpleNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jTxtStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setName("jPanel4"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setName("jPanel5"); // NOI18N

        buttonGroup2.add(jrdbSimpleAZaz);
        jrdbSimpleAZaz.setText(resourceMap.getString("jrdbSimpleAZaz.text")); // NOI18N
        jrdbSimpleAZaz.setName("jrdbSimpleAZaz"); // NOI18N

        jcmbCapSmall.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "a-z", "A-Z", "0-9" }));
        jcmbCapSmall.setName("jcmbCapSmall"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jcmbCapSmallLength.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26" }));
        jcmbCapSmallLength.setName("jcmbCapSmallLength"); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrdbSimpleAZaz, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcmbCapSmall, 0, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcmbCapSmallLength, 0, 59, Short.MAX_VALUE)
                .addGap(617, 617, 617))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jrdbSimpleAZaz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcmbCapSmall, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jcmbCapSmallLength, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setName("jPanel6"); // NOI18N

        buttonGroup2.add(jrdbSimpleCustom);
        jrdbSimpleCustom.setText(resourceMap.getString("jrdbSimpleCustom.text")); // NOI18N
        jrdbSimpleCustom.setName("jrdbSimpleCustom"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jcmbCustomLength.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26" }));
        jcmbCustomLength.setName("jcmbCustomLength"); // NOI18N

        jtxtCharacterList.setName("jtxtCharacterList"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrdbSimpleCustom)
                .addGap(105, 105, 105)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jcmbCustomLength, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtxtCharacterList, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcmbCustomLength, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addComponent(jtxtCharacterList, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                    .addComponent(jrdbSimpleCustom, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jrdbUrl.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jrdbUrl.setName("jrdbUrl"); // NOI18N

        buttonGroup1.add(jrdbSimple);
        jrdbSimple.setSelected(true);
        jrdbSimple.setText(resourceMap.getString("jrdbSimple.text")); // NOI18N
        jrdbSimple.setName("jrdbSimple"); // NOI18N

        buttonGroup1.add(jrdbCustom);
        jrdbCustom.setText(resourceMap.getString("jrdbCustom.text")); // NOI18N
        jrdbCustom.setName("jrdbCustom"); // NOI18N

        buttonGroup1.add(jrdbURL);
        jrdbURL.setText(resourceMap.getString("jrdbURL.text")); // NOI18N
        jrdbURL.setName("jrdbURL"); // NOI18N

        javax.swing.GroupLayout jrdbUrlLayout = new javax.swing.GroupLayout(jrdbUrl);
        jrdbUrl.setLayout(jrdbUrlLayout);
        jrdbUrlLayout.setHorizontalGroup(
            jrdbUrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jrdbUrlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jrdbUrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrdbSimple)
                    .addComponent(jrdbURL)
                    .addComponent(jrdbCustom))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jrdbUrlLayout.setVerticalGroup(
            jrdbUrlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jrdbUrlLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jrdbSimple, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(153, 153, 153)
                .addComponent(jrdbCustom, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addGap(133, 133, 133)
                .addComponent(jrdbURL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(174, 174, 174))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrdbUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 726, Short.MAX_VALUE)
                                .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jrdbUrl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(generateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
        );

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        settingMenu.setText(resourceMap.getString("settingMenu.text")); // NOI18N
        settingMenu.setName("settingMenu"); // NOI18N

        genSettingMenuItem.setAction(actionMap.get("generalSettings_MenuItem")); // NOI18N
        genSettingMenuItem.setText(resourceMap.getString("genSettingMenuItem.text")); // NOI18N
        genSettingMenuItem.setName("genSettingMenuItem"); // NOI18N
        settingMenu.add(genSettingMenuItem);

        smtpSettingMenuItem.setAction(actionMap.get("generateWordListGmailSetting_menuclick")); // NOI18N
        smtpSettingMenuItem.setText(resourceMap.getString("smtpSettingMenuItem.text")); // NOI18N
        smtpSettingMenuItem.setName("smtpSettingMenuItem"); // NOI18N
        settingMenu.add(smtpSettingMenuItem);

        menuBar.add(settingMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setText(resourceMap.getString("aboutMenuItem.text")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 1204, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1184, Short.MAX_VALUE)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel))
                .addGap(3, 3, 3))
        );

        progressBar.setName("progressBar"); // NOI18N

        setComponent(mainPanel);
        setMenuBar(menuBar);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    

    @Action
    public void generalSettings_MenuItem() {
        if (wordListGeneralSettingDialog == null) {
            JFrame mainFrame = WordListGeneratorApp.getApplication().getMainFrame();
            wordListGeneralSettingDialog = new WordListGeneralSetting(mainFrame);
            wordListGeneralSettingDialog.setLocationRelativeTo(mainFrame);
        }
        WordListGeneratorApp.getApplication().show(wordListGeneralSettingDialog);
    }

    @Action
    public void generateWordListGmailSetting_menuclick() {
        if (wordListGmailSettingDialog == null) {
            JFrame mainFrame = WordListGeneratorApp.getApplication().getMainFrame();
            wordListGmailSettingDialog = new WordListGmailSetting(mainFrame);
            wordListGmailSettingDialog.setLocationRelativeTo(mainFrame);
        }
        WordListGeneratorApp.getApplication().show(wordListGmailSettingDialog);
    }
    @Action
    public void generateWordList() {
        if (!FileManager.folderExists(WordListGeneratorApp.getApplication().setting.getFolderLocation())) {
            JOptionPane.showMessageDialog(null, "Output folder is not set.");
            return;
        }
        boolean bIsShowProgress = true;
        JFrame mainFrame = WordListGeneratorApp.getApplication().getMainFrame();
        jProgressBar = new WordListGeneratorProgressBar(mainFrame);
        if (jrdbSimple.isSelected()) {
            if (jrdbSimpleNumber.isSelected()) {
                WordListGen wordListGen = new WordListGen();
                wordListGen.setWordListGeneratorProgressBar(jProgressBar);
                Thread wordListThread = new Thread(wordListGen);
                if (jTxtStart.getText().length() > 0 && jTxtEnd.getText().length() > 0) {
                    try {
                        int start = Integer.parseInt(jTxtStart.getText());
                        int end = Integer.parseInt(jTxtEnd.getText());
                        wordListGen.setFileName("simple");
                        char[] charList = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',};
                        wordListGen.setAlphabet(charList);
                        wordListGen.setIsFixLength(false);
                        wordListGen.setWordLength(jTxtEnd.getText().length());
                        wordListGen.setStart(start);
                        wordListGen.setEnd(end);
                        wordListThread.start();
                    } catch (NumberFormatException numberFormatException) {
                        bIsShowProgress = false;
                        JOptionPane.showMessageDialog(null, "Start and end values is not valid.");                        
                    }
                } else {
                    bIsShowProgress = false;
                    JOptionPane.showMessageDialog(null, "Start and end values cannot be empty.");
                }

            } else if (jrdbSimpleAZaz.isSelected()) {
                WordListGen wordListGen = new WordListGen();
                wordListGen.setWordListGeneratorProgressBar(jProgressBar);
                Thread wordListThread = new Thread(wordListGen);
                int wordLength = Integer.parseInt(jcmbCapSmallLength.getSelectedItem().toString());
                wordListGen.setIsFixLength(true);
                if (jcmbCapSmall.getSelectedItem().toString().equals("a-z")) {
                    char[] charList = {'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'e', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'};
                    wordListGen.setFileName("simplea-z");
                    wordListGen.setAlphabet(charList);
                    wordListGen.setWordLength(wordLength);
                    wordListThread.start();
                } else if (jcmbCapSmall.getSelectedItem().toString().equals("A-Z")) {
                    wordListGen.setFileName("simpleA-Z");
                    char[] charList = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'G', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'};
                    wordListGen.setAlphabet(charList);
                    wordListGen.setWordLength(wordLength);
                    wordListThread.start();
                } else if (jcmbCapSmall.getSelectedItem().toString().equals("0-9")) {
                    wordListGen.setFileName("simple0-9");
                    char[] charList = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9'};
                    wordListGen.setAlphabet(charList);
                    wordListGen.setWordLength(wordLength);
                    wordListThread.start();
                }
            } else if (jrdbSimpleCustom.isSelected()) {
                WordsListGen wordsListGen = new WordsListGen();
                wordsListGen.setWordListGeneratorProgressBar(jProgressBar);
                Thread wordsListThread = new Thread(wordsListGen);
                int wordLength = Integer.parseInt(jcmbCustomLength.getSelectedItem().toString());
                String[] strList = jtxtCharacterList.getText().split(",");
                wordsListGen.setFileName("simpleCustom");
                wordsListGen.setAlphabet(strList);
                wordsListGen.setWordLength(wordLength);
                wordsListThread.start();
            }
        } else if (jrdbCustom.isSelected()) {
            CustomWordListGen customWordListGen = new CustomWordListGen();
            customWordListGen.setWordListGeneratorProgressBar(jProgressBar);
            Thread customWordListThread = new Thread(customWordListGen);
            customWordListGen.setFileName("custom");
            customWordListGen.setStrText(jtxtWordList.getText());
            if (jChkRemoveDuplicateCustom.isSelected()){
                customWordListGen.setRemoveDuplicate(true);
            }else{
                customWordListGen.setRemoveDuplicate(false);
            }
            customWordListThread.start();
        } else if (jrdbURL.isSelected()) {
            CustomWordListGen customWordListGen = new CustomWordListGen();
            customWordListGen.setWordListGeneratorProgressBar(jProgressBar);
            Thread customWordListThread = new Thread(customWordListGen);
            String str = GetURLContent.getURLContent(jtxtURL.getText());
            if (jChkRemoveDuplicate.isSelected()){
                customWordListGen.setRemoveDuplicate(true);
            }else{
                customWordListGen.setRemoveDuplicate(false);
            }
            //System.out.println(str);
            customWordListGen.setFileName("customURL");
            customWordListGen.setStrText(str);
            customWordListThread.start();
        }
        if (bIsShowProgress){
            jProgressBar.setLocationRelativeTo(mainFrame);
            jProgressBar.setModal(true);
            jProgressBar.setVisible(true);
        }        
    }

   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JMenuItem genSettingMenuItem;
    private javax.swing.JButton generateButton;
    private javax.swing.JCheckBox jChkRemoveDuplicate;
    private javax.swing.JCheckBox jChkRemoveDuplicateCustom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtEnd;
    private javax.swing.JTextField jTxtStart;
    private javax.swing.JComboBox jcmbCapSmall;
    private javax.swing.JComboBox jcmbCapSmallLength;
    private javax.swing.JComboBox jcmbCustomLength;
    private javax.swing.JRadioButton jrdbCustom;
    private javax.swing.JRadioButton jrdbSimple;
    private javax.swing.JRadioButton jrdbSimpleAZaz;
    private javax.swing.JRadioButton jrdbSimpleCustom;
    private javax.swing.JRadioButton jrdbSimpleNumber;
    private javax.swing.JRadioButton jrdbURL;
    private javax.swing.JPanel jrdbUrl;
    private javax.swing.JTextField jtxtCharacterList;
    private javax.swing.JTextField jtxtURL;
    private javax.swing.JTextArea jtxtWordList;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JMenu settingMenu;
    private javax.swing.JMenuItem smtpSettingMenuItem;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
    private JDialog wordListDialog;
    private JDialog wordListGeneralSettingDialog;
    private JDialog wordListGmailSettingDialog;
}
