/*
 * WordListGeneratorAboutBox.java
 */

package wordlistgenerator;

import org.jdesktop.application.FrameView;

public class WordListGeneratorProgressBar extends javax.swing.JDialog {
    
    static boolean showBar;
    
    public WordListGeneratorProgressBar(java.awt.Frame parent) {
        super(parent);
        initComponents(); 
        showBar = true;
        new Thread(new thread1()).start();
    }

    public boolean isShowBar() {
        return showBar;
    }

    public void setShowBar(boolean showBar) {
        this.showBar = showBar;
    }
    
    public  void destroy(){
       
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(wordlistgenerator.WordListGeneratorApp.class).getContext().getResourceMap(WordListGeneratorProgressBar.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);
        setUndecorated(true);

        jProgressBar.setName("jProgressBar"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    static javax.swing.JProgressBar jProgressBar;
    // End of variables declaration//GEN-END:variables
    public static class thread1 implements Runnable {

        public void run() {
            int i = 0;
            while (showBar) { //Progressively increment variable i                
                jProgressBar.setValue(i); //Set value
                jProgressBar.repaint(); //Refresh graphics
                try {
                    Thread.sleep(50);
                } //Sleep 50 milliseconds                
                catch (InterruptedException err) {
                }
                i++;
                if (i==100){
                    i=0;
                }
            }            
        }
    }
}
