/*
 * WordListGeneratorAboutBox.java
 */
package wordlistgenerator;

import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.jdesktop.application.Action;
import wordlistgenerator.bl.Setting;

public class WordListGeneralSetting extends javax.swing.JDialog {

    private Setting setting;

    public WordListGeneralSetting(java.awt.Frame parent) {
        super(parent);
        initComponents();
        getRootPane().setDefaultButton(closeButton);
        this.setting = WordListGeneratorApp.getApplication().setting;
        loadSettings();
    }

    private void loadSettings() {
        jchkLeetSpeak.setSelected(setting.isSupportLeekSpeak());
        jchkAddSpaceInWords.setSelected(setting.isAddSpace());
        jchkMakeFirstLetterCapital.setSelected(setting.isMakeFirstLetterCapital());
        jchkMakeEndLetterCapital.setSelected(setting.isMakeLastLetterCapital());
        jchkAddCharInBegin.setSelected(setting.isBeginWord());
        jchkAddCharAtEnd.setSelected(setting.isEndWord());
        JtxtBeginWord.setText(setting.getBeginWords());
        jtxtEndWord.setText(setting.getEndWords());
        jtxtFolderLocation.setText(setting.getFolderLocation());
        jtxtFileSize.setText(setting.getFileSize()+"");
    }

    @Action
    public void closeAboutBox() {
        boolean bIsOk = true;
        setting.setFolderLocation(jtxtFolderLocation.getText());
        setting.setSupportLeekSpeak(jchkLeetSpeak.isSelected());
        setting.setAddSpace(jchkAddSpaceInWords.isSelected());
        setting.setMakeFirstLetterCapital(jchkMakeFirstLetterCapital.isSelected());
        setting.setMakeLastLetterCapital(jchkMakeEndLetterCapital.isSelected());
        if (jtxtFileSize.getText().length()>0){
            try{
                setting.setFileSize(Integer.parseInt(jtxtFileSize.getText()));
            }catch (Exception ex){
                setting.setFileSize(0);
            }            
        }
        
        if (jchkAddCharInBegin.isSelected()) {
            if (JtxtBeginWord.getText().length() > 0) {
                setting.setBeginWord(true);
                setting.setBeginWords(JtxtBeginWord.getText());
            } else {
                JOptionPane.showMessageDialog(this, "Begin word can't be empty.");
                setting.setBeginWord(false);
                bIsOk = false;
            }
        } else {
            setting.setBeginWord(false);
        }

        if (jchkAddCharAtEnd.isSelected()) {
            if (jtxtEndWord.getText().length() > 0) {
                setting.setEndWord(true);
                setting.setEndWords(jtxtEndWord.getText());
            } else {
                JOptionPane.showMessageDialog(this, "End word can't be empty.");
                setting.setEndWord(false);
                bIsOk = false;
            }
        } else {
            setting.setEndWord(false);
        }
        if (bIsOk) {
            try {
                FileOutputStream fileOut = new FileOutputStream("Setting.ser");
                ObjectOutputStream out = new ObjectOutputStream(fileOut);
                out.writeObject(setting);
                out.close();
                fileOut.close();

            } catch (IOException ie) {
                ie.printStackTrace();
            }
            dispose();
        }

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        jchkLeetSpeak = new javax.swing.JCheckBox();
        jchkAddCharInBegin = new javax.swing.JCheckBox();
        jchkAddCharAtEnd = new javax.swing.JCheckBox();
        JtxtBeginWord = new javax.swing.JTextField();
        jtxtEndWord = new javax.swing.JTextField();
        jchkAddSpaceInWords = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jtxtFolderLocation = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jchkMakeFirstLetterCapital = new javax.swing.JCheckBox();
        jchkMakeEndLetterCapital = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jtxtFileSize = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(wordlistgenerator.WordListGeneratorApp.class).getContext().getResourceMap(WordListGeneralSetting.class);
        setTitle(resourceMap.getString("title")); // NOI18N
        setModal(true);
        setName("aboutBox"); // NOI18N
        setResizable(false);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(wordlistgenerator.WordListGeneratorApp.class).getContext().getActionMap(WordListGeneralSetting.class, this);
        closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N

        jchkLeetSpeak.setText(resourceMap.getString("jchkLeetSpeak.text")); // NOI18N
        jchkLeetSpeak.setName("jchkLeetSpeak"); // NOI18N

        jchkAddCharInBegin.setText(resourceMap.getString("jchkAddCharInBegin.text")); // NOI18N
        jchkAddCharInBegin.setName("jchkAddCharInBegin"); // NOI18N

        jchkAddCharAtEnd.setText(resourceMap.getString("jchkAddCharAtEnd.text")); // NOI18N
        jchkAddCharAtEnd.setName("jchkAddCharAtEnd"); // NOI18N

        JtxtBeginWord.setText(resourceMap.getString("JtxtBeginWord.text")); // NOI18N
        JtxtBeginWord.setName("JtxtBeginWord"); // NOI18N

        jtxtEndWord.setText(resourceMap.getString("jtxtEndWord.text")); // NOI18N
        jtxtEndWord.setName("jtxtEndWord"); // NOI18N

        jchkAddSpaceInWords.setText(resourceMap.getString("jchkAddSpaceInWords.text")); // NOI18N
        jchkAddSpaceInWords.setName("jchkAddSpaceInWords"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jtxtFolderLocation.setText(resourceMap.getString("jtxtFolderLocation.text")); // NOI18N
        jtxtFolderLocation.setEnabled(false);
        jtxtFolderLocation.setName("jtxtFolderLocation"); // NOI18N

        jButton1.setAction(actionMap.get("browse_click")); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N

        jchkMakeFirstLetterCapital.setText(resourceMap.getString("jchkMakeFirstLetterCapital.text")); // NOI18N
        jchkMakeFirstLetterCapital.setName("jchkMakeFirstLetterCapital"); // NOI18N

        jchkMakeEndLetterCapital.setText(resourceMap.getString("jchkMakeEndLetterCapital.text")); // NOI18N
        jchkMakeEndLetterCapital.setName("jchkMakeEndLetterCapital"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jtxtFileSize.setName("jtxtFileSize"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchkLeetSpeak)
                            .addComponent(jchkAddCharInBegin)
                            .addComponent(jchkMakeEndLetterCapital)
                            .addComponent(jchkMakeFirstLetterCapital)
                            .addComponent(jchkAddSpaceInWords))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JtxtBeginWord, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jchkAddCharAtEnd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtEndWord, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jtxtFileSize, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(jtxtFolderLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(closeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jchkLeetSpeak)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jchkAddCharInBegin)
                    .addComponent(JtxtBeginWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jchkAddCharAtEnd)
                    .addComponent(jtxtEndWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jchkAddSpaceInWords)
                .addGap(18, 18, 18)
                .addComponent(jchkMakeFirstLetterCapital)
                .addGap(18, 18, 18)
                .addComponent(jchkMakeEndLetterCapital)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFolderLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFileSize, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeButton))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Action
    public void browse_click() {
        JFileChooser chooser;
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Select folder");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        // disable the "All files" option.
        //
        chooser.setAcceptAllFileFilterUsed(false);
        //    
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            jtxtFolderLocation.setText(chooser.getSelectedFile().toString());
        } else {
            System.out.println("No Selection ");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtxtBeginWord;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox jchkAddCharAtEnd;
    private javax.swing.JCheckBox jchkAddCharInBegin;
    private javax.swing.JCheckBox jchkAddSpaceInWords;
    private javax.swing.JCheckBox jchkLeetSpeak;
    private javax.swing.JCheckBox jchkMakeEndLetterCapital;
    private javax.swing.JCheckBox jchkMakeFirstLetterCapital;
    private javax.swing.JTextField jtxtEndWord;
    private javax.swing.JTextField jtxtFileSize;
    private javax.swing.JTextField jtxtFolderLocation;
    // End of variables declaration//GEN-END:variables
}
